import json

fileObject = open("output.json", "r")
jsonContent = fileObject.read()
aList = json.loads(jsonContent)
print(aList)
print('\n')
print(aList['1'])
print("--------")
print(aList['2'])
print("--------")
print(aList['3'])
print("--------")
print(aList['rest'])
print("--------")
print(aList.values())